// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RecreationDbContext))]
    [Migration("20210618174047_TryFixMigration")]
    partial class TryFixMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recreation_service")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Entities.AdditionalService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecreationObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecreationObjectId");

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecreationObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecreationObjectId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Domain.Entities.HealingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecreationObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecreationObjectId");

                    b.ToTable("HealingMethods");
                });

            modelBuilder.Entity("Domain.Entities.RecreationObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RecreationObjects");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UserUid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<string>("RecreationEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecreationObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecreationObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("Domain.Entities.AdditionalService", b =>
                {
                    b.HasOne("Domain.Entities.RecreationObject", null)
                        .WithMany("AdditionalServices")
                        .HasForeignKey("RecreationObjectId");
                });

            modelBuilder.Entity("Domain.Entities.Disease", b =>
                {
                    b.HasOne("Domain.Entities.RecreationObject", null)
                        .WithMany("Diseases")
                        .HasForeignKey("RecreationObjectId");
                });

            modelBuilder.Entity("Domain.Entities.HealingMethod", b =>
                {
                    b.HasOne("Domain.Entities.RecreationObject", null)
                        .WithMany("HealingMethods")
                        .HasForeignKey("RecreationObjectId");
                });

            modelBuilder.Entity("Domain.Entities.RecreationObject", b =>
                {
                    b.OwnsOne("Domain.Entities.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("RecreationObjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("Website")
                                .HasColumnType("text");

                            b1.HasKey("RecreationObjectId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("RecreationObjectId");
                        });

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Domain.Entities.UserMessage", b =>
                {
                    b.HasOne("Domain.Entities.RecreationObject", null)
                        .WithMany("UserMessages")
                        .HasForeignKey("RecreationObjectId");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("UserMessages")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.Entities.RecreationObject", b =>
                {
                    b.Navigation("AdditionalServices");

                    b.Navigation("Diseases");

                    b.Navigation("HealingMethods");

                    b.Navigation("UserMessages");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("UserMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
